# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
