# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='vm_disks1',
            field=models.IntegerField(default=0),
        ),
    ]
