# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0002_vms_vm_disks1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vms',
            name='vm_disks1',
        ),
    ]
