# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0004_auto_20170913_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vms',
            name='vm_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
