# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0005_auto_20170913_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
